### ISSUE TITLE
The QIF projects has a problem when runing at pyqpand

### ISSUE THREAD

**Issue by dengzhen789** [OriginQ/pyQPanda-Toturial#19]
the result is [(0, 0.24999994039535522), (2, 0.24999994039535522), (4, 0.24999994039535522), (6, 0.24999994039535522), (1, 0.0), (3, 0.0), (5, 0.0), (7, 0.0)] and doesn't change,why?

**Comment by shenzhi-git** [comment]
这是上个版本的bug，将在这周会更新版本，修复这个问题
