### ISSUE TITLE
NameError: name 'Shor_factorization' is not defined

### ISSUE THREAD

**Issue by EdQzz** [OriginQ/pyQPanda-Toturial#79]
`#!/usr/bin/env python

from pyqpanda import *

if __name__ == "__main__":

   N=15
   r = Shor_factorization(N)
   print(r)`

python程序执行时报错"NameError: name 'Shor_factorization' is not defined"

**Comment by tianshidebeisang** [comment]
i hava the same question

**Comment by a234106261** [comment]
相关python接口变动很大，出于稳定性考虑，便利的接口函数Shor_factorization目前没有出现在正式版pyqpanda中。
目前只能通过已有的C++接口来调用Shor算法，例子可以参考test中的Shor test。
后续的大版本更新时会将包含Shor_factorization在内的多处重大改动一并上线。
